site_name:           Mortgage.jl
repo_url:            https://github.com/holder66/Mortgage.jl
site_description:    Description
site_author:         Henry Olders
copyright:           © Henry Olders 2016
theme:               readthedocs

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- About: index.md
- Usage: usage.md
- DocTests: doctests.md
